version: '3.9'

services:
  agent:
    build: .
    container_name: agent
    environment:
      PROMETHEUS_URL: 'http://victoriametrics:8428'
#      this one is for victoria
      INITIAL_OFFSET: "1657284343"
#      this one is for prometheus
#      INITIAL_OFFSET: "1658275200"
#      S3_REGION: 'us-east-1'
#      S3_BUCKET: 'prometheus-agent-test'
      CUSTOMER_NAME: 'dev'
      CLUSTER_NAME: 'prometheus-stack'

      DATA_SENDER: 'dummy'
      MONITORING: 'dummy'
      MONITORING_TOKEN: 'dummy'

      CRON_SCHEDULE: "* * * * *"
      DATA_DIR: '/usr/src/app/data'
      RUN_BY_ONE_ITERATION: 'true'
    volumes:
      - ./data:/usr/src/app/data
      - ./logs/:/var/log/
      - ./src/:/usr/src/app/src/
    depends_on:
      - victoriametrics

  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:v1.78.1
    ports:
      - "8428:8428"
    volumes:
      - /storage
    command:
      - '--storageDataPath=/storage'
      - '--httpListenAddr=:8428'
      - '--retentionPeriod=10y'
    restart: always
